apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
  labels:
    name: pv-pod
spec:
  containers:
  - name: alpine
    image: alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: <Port>
