apiVersion: v1
kind: Pod
metadata:
  name: redis-emptydir
  labels:
    name: redis-emptydir
spec:
  containers:
    - name: redis
      image: redis
      volumeMounts:
        - name: redis-storage
          mountPath: /data/redis
  volumes:
    - name: redis-storage
      emptyDir: {}