apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  labels:
    name: hostpath-pod
spec:
  volumes:
    - name: hostpath-vol
      hostPath:
        path: /var/tmp
  containers:
    - name: hostpath-pod
      image: alpine
      command:
      - /bin/sh
      - -c
      - |
        apk update && apk add --no-cache curl && echo Kubernetes DevOps on HostVolume - $(date) >> /output/output.txt && sleep 3600
      volumeMounts:
        - name: hostpath-vol
          mountPath: /output
