apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
  labels:
    name: pvc-pod
spec:
  restartPolicy: Never
  containers:
    - name: alpine
      image: alpine
      command: ["sh", "-c", "echo Hello Kubernetes, We learn Persistent Volume Claim >> /output/test.txt"]
      volumeMounts:
        - mountPath: /output
          name: pod-vol
  volumes:
    - name: pod-vol
      persistentVolumeClaim:
        claimName: static-pvc # come from persistent-volume-claim.yaml